#!/usr/bin/env ruby

def rake_silent_tasks
dotcache = "#{File.join(File.expand_path('~'), ".raketabs-#{Dir.pwd.hash}")}"
if File.exists?(dotcache)
Marshal.load(File.read(dotcache))
else
require 'rubygems'
require 'rake'
load 'Rakefile'
tasks = Rake.application.tasks.map(&:name)
File.open(dotcache, 'w') { |f| f.puts Marshal.dump(tasks) }
tasks || []
end
end

exit 0 unless File.file?(File.join(Dir.pwd, 'Rakefile'))
exit 0 unless matches = ENV["COMP_LINE"].match(/^rake\s+(.*)/)

after_match = matches[1]
task_match = after_match.strip.empty? ? nil : after_match.strip.split.last

if task_match
tasks = rake_silent_tasks.grep /^#{Regexp.escape task_match}/

# handle namespaces
if matches = task_match.match(/^([-\w:]+:)(.*)/)
upto_last_colon = matches[1]
after_match = matches[2]
tasks = tasks.map { |t| (t =~ /^#{Regexp.escape upto_last_colon}([-\w:]+)$/) ? "#{$1}" : t }
end
puts tasks
end

exit 0
